(()=>{
  let ctx=null,master=null,musicGain=null,sfxGain=null,musicTimer=null,enabled=false,musicOn=true,pack=localStorage.getItem('kiwi-sound-pack')||'classic';
  const channel=('BroadcastChannel' in window)?new BroadcastChannel('kiwi-feud-sound-v1'):null;
  function ensure(){if(ctx)return;ctx=new (window.AudioContext||window.webkitAudioContext)();master=ctx.createGain();master.gain.value=.72;master.connect(ctx.destination);musicGain=ctx.createGain();musicGain.gain.value=.13;musicGain.connect(master);sfxGain=ctx.createGain();sfxGain.gain.value=.9;sfxGain.connect(master)}
  async function unlock(){ensure();if(ctx.state==='suspended')await ctx.resume()}
  function tone(freq,dur=.12,type='sine',vol=.15,when=0,dest=sfxGain,slide=null){if(!enabled)return;ensure();const t=ctx.currentTime+when,o=ctx.createOscillator(),g=ctx.createGain();o.type=type;o.frequency.setValueAtTime(freq,t);if(slide)o.frequency.exponentialRampToValueAtTime(slide,t+dur);o.connect(g);g.connect(dest||sfxGain);g.gain.setValueAtTime(Math.max(.001,vol),t);g.gain.exponentialRampToValueAtTime(.001,t+dur);o.start(t);o.stop(t+dur+.04)}
  function noise(dur=.22,vol=.08,when=0,frequency=900){if(!enabled)return;ensure();const t=ctx.currentTime+when,b=ctx.createBuffer(1,ctx.sampleRate*dur,ctx.sampleRate),d=b.getChannelData(0);for(let i=0;i<d.length;i++)d[i]=(Math.random()*2-1)*(1-i/d.length);const src=ctx.createBufferSource(),f=ctx.createBiquadFilter(),g=ctx.createGain();src.buffer=b;f.type='bandpass';f.frequency.value=frequency;f.Q.value=.7;g.gain.value=vol;src.connect(f);f.connect(g);g.connect(sfxGain);src.start(t);src.stop(t+dur)}
  function brass(notes,start=0,dur=.28,vol=.09){notes.forEach((n,i)=>{tone(n,dur,'sawtooth',vol,start+i*.055,sfxGain,n*1.01);tone(n*2,dur*.72,'square',vol*.18,start+i*.055,sfxGain)})}
  function chord(notes,dur=.65,vol=.024,when=0){notes.forEach((n,i)=>tone(n,dur,i%2?'triangle':'sine',vol,when,musicGain))}
  function stopMusic(){if(musicTimer){clearInterval(musicTimer);musicTimer=null}}
  function startMusic(){stopMusic();if(!enabled||!musicOn)return;let step=0;const banks={classic:[[196,246.94,293.66],[220,261.63,329.63],[174.61,220,261.63],[196,246.94,311.13]],pub:[[146.83,196,246.94],[164.81,220,261.63],[130.81,174.61,220],[146.83,196,246.94]],arcade:[[261.63,329.63,392],[293.66,369.99,440],[220,293.66,369.99],[246.94,311.13,392]]};const p=banks[pack]||banks.classic;const tick=()=>{if(!enabled||!musicOn)return;const c=p[step++%p.length];chord(c,1.45,.021);tone(c[0]/2,.18,pack==='arcade'?'square':'sine',.035,0,musicGain);tone(c[1],.07,'triangle',.018,.36,musicGain);tone(c[2],.08,'triangle',.017,.76,musicGain)};tick();musicTimer=setInterval(tick,1550)}
  function reveal(){if(pack==='arcade'){tone(740,.08,'square',.10);tone(988,.12,'square',.11,.07);tone(1318,.16,'triangle',.13,.14)}else if(pack==='pub'){tone(523.25,.09,'triangle',.08);tone(659.25,.16,'sine',.12,.08);noise(.1,.018,.06,1800)}else{brass([659.25,783.99,987.77],0,.18,.075);tone(1318.5,.25,'triangle',.12,.15)}}
  function topAnswer(){if(pack==='arcade'){[659,784,988,1318].forEach((n,i)=>tone(n,.18,'square',.10,i*.07));noise(.18,.035,.15,2100)}else{brass([523.25,659.25,783.99,1046.5],0,.25,.09);tone(1568,.4,'triangle',.13,.24);noise(.18,.035,.18,1600)}}
  function buzzer(){if(pack==='arcade'){tone(180,.48,'square',.28,0,sfxGain,70);tone(90,.55,'sawtooth',.16,.02,sfxGain,48);noise(.34,.1,0,600)}else if(pack==='pub'){tone(132,.58,'sawtooth',.32,0,sfxGain,75);tone(66,.74,'square',.18,.02,sfxGain,46);noise(.48,.13,0,520)}else{tone(145,.52,'sawtooth',.30,0,sfxGain,82);tone(72,.7,'square',.18,.02,sfxGain,55);noise(.42,.12,0)} }
  function faceoff(){if(pack==='arcade'){tone(392,.09,'square',.08);tone(523,.1,'square',.09,.08);tone(784,.22,'triangle',.12,.17)}else{brass([392,523.25,659.25],0,.18,.075);tone(783.99,.28,'triangle',.10,.18)}}
  function steal(){tone(220,.18,'sawtooth',.07);tone(196,.22,'sawtooth',.075,.2);tone(174.61,.28,'sawtooth',.08,.43);noise(.2,.025,.58,700);tone(440,.12,'square',.09,.7)}
  function crowd(){noise(.8,.055,0,1300);noise(.65,.035,.12,2100);tone(440,.09,'triangle',.025,.08);tone(523,.09,'triangle',.022,.19)}
  function win(){brass([523.25,659.25,783.99,1046.5],0,.34,.095);brass([659.25,783.99,987.77,1318.5],.28,.42,.08);noise(.42,.06,.28,1500);setTimeout(crowd,220)}
  function countdown(){tone(880,.08,'square',.08);tone(660,.08,'square',.06,.11)}
  async function setEnabled(value){await unlock();enabled=!!value;if(enabled){startMusic();faceoff()}else stopMusic();updateButtons();return enabled}
  function setMusic(value){musicOn=!!value;if(musicOn)startMusic();else stopMusic();updateButtons()}
  function setPack(value){pack=['classic','pub','arcade'].includes(value)?value:'classic';localStorage.setItem('kiwi-sound-pack',pack);if(enabled&&musicOn)startMusic();document.querySelectorAll('[data-sound-pack]').forEach(b=>b.classList.toggle('gold',b.dataset.soundPack===pack));channel?.postMessage({type:'pack',value:pack})}
  function handle(msg){if(!msg)return;if(msg.type==='enable')setEnabled(msg.value);if(msg.type==='music')setMusic(msg.value);if(msg.type==='pack'){pack=msg.value;if(enabled&&musicOn)startMusic()}if(msg.type==='correct'||msg.type==='reveal')reveal();if(msg.type==='topAnswer')topAnswer();if(msg.type==='buzzer')buzzer();if(msg.type==='win')win();if(msg.type==='faceoff')faceoff();if(msg.type==='steal')steal();if(msg.type==='crowd')crowd();if(msg.type==='countdown')countdown()}
  if(channel)channel.onmessage=e=>handle(e.data);
  function send(type,data={}){handle({type,...data});if(channel)channel.postMessage({type,...data})}
  window.KiwiAudio={enable:async value=>{const on=await setEnabled(value);if(channel)channel.postMessage({type:'enable',value:on});return on},music:value=>{setMusic(value);if(channel)channel.postMessage({type:'music',value:musicOn})},pack:setPack,ping:()=>send('reveal'),correct:()=>send('reveal'),reveal:()=>send('reveal'),topAnswer:()=>send('topAnswer'),buzzer:()=>send('buzzer'),win:()=>send('win'),question:()=>send('faceoff'),faceoff:()=>send('faceoff'),steal:()=>send('steal'),crowd:()=>send('crowd'),countdown:()=>send('countdown'),isEnabled:()=>enabled};
  let toggle,musicToggle;
  function updateButtons(){if(toggle)toggle.textContent=enabled?'🔇 Sound On — Tap to Mute':'🔊 Enable Game Sound';if(musicToggle)musicToggle.textContent=musicOn?'🎵 Background On':'🎵 Background Off'}
  if(document.title.includes('Host')){
    const panel=document.createElement('section');panel.className='panel soundboard-panel';panel.style.cssText='position:static;margin:12px auto 0;max-width:820px;background:#102f4e;border:1px solid #ffffff24;border-radius:14px;padding:10px;box-shadow:none';
    panel.innerHTML='<details><summary style="cursor:pointer;font-weight:1000;color:#ffd24b;display:flex;justify-content:space-between;gap:8px"><span>🎺 Original Royalty-Free Soundboard</span><span style="font-size:12px;color:#b6ccda">Tap to open</span></summary><div style="display:grid;grid-template-columns:repeat(3,minmax(0,1fr));gap:7px;margin-top:10px"><button class="btn" data-sound-pack="classic">Classic Show</button><button class="btn" data-sound-pack="pub">Kiwi Pub</button><button class="btn" data-sound-pack="arcade">Arcade</button></div><div style="display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:8px;margin-top:8px"><button id="audioToggle" class="btn gold">🔊 Enable Game Sound</button><button id="musicToggle" class="btn">🎵 Background On</button><button id="audioPing" class="btn green">✅ Answer Reveal</button><button id="audioTop" class="btn gold">⭐ Top Answer</button><button id="audioBuzz" class="btn red">❌ Big Buzzer</button><button id="audioSteal" class="btn">⚡ Steal Sting</button><button id="audioFaceoff" class="btn">🎤 Face-Off Cue</button><button id="audioCrowd" class="btn">👏 Crowd Reaction</button><button id="audioWin" class="btn gold" style="grid-column:1/-1">🏆 Round Win</button></div><div style="font-size:11px;color:#b6ccda;text-align:center;margin-top:7px">All sounds are generated in-browser and original, so no third-party copyrighted audio files are used.</div></details>';
    document.querySelector('main')?.appendChild(panel);toggle=panel.querySelector('#audioToggle');musicToggle=panel.querySelector('#musicToggle');toggle.onclick=()=>window.KiwiAudio.enable(!enabled);musicToggle.onclick=()=>window.KiwiAudio.music(!musicOn);panel.querySelectorAll('[data-sound-pack]').forEach(b=>b.onclick=()=>setPack(b.dataset.soundPack));panel.querySelector('#audioPing').onclick=()=>window.KiwiAudio.reveal();panel.querySelector('#audioTop').onclick=()=>window.KiwiAudio.topAnswer();panel.querySelector('#audioBuzz').onclick=()=>window.KiwiAudio.buzzer();panel.querySelector('#audioSteal').onclick=()=>window.KiwiAudio.steal();panel.querySelector('#audioFaceoff').onclick=()=>window.KiwiAudio.faceoff();panel.querySelector('#audioCrowd').onclick=()=>window.KiwiAudio.crowd();panel.querySelector('#audioWin').onclick=()=>window.KiwiAudio.win();setPack(pack);const downloadScript=document.createElement('script');downloadScript.src='downloads.js';document.body.appendChild(downloadScript)
  }else{const unlockBtn=document.createElement('button');unlockBtn.textContent='🔊 Enable Audience Sound';unlockBtn.style.cssText='position:fixed;right:12px;bottom:12px;z-index:9999;border:0;border-radius:12px;padding:10px 13px;font-weight:900;background:#ffd24b;color:#251700';document.body.appendChild(unlockBtn);unlockBtn.onclick=async()=>{await setEnabled(true);unlockBtn.remove()}}
})();